<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Fix absolute URLs generated by Laravel behind proxies if they are dropping the subfolder mappings
        if (app()->environment('production')) {
            URL::forceRootUrl(config('app.url'));
            
            // Note: If you have an SSL certificate on cPanel, uncomment the line below to force HTTPS:
            // URL::forceScheme('https');
        }
    }
}
